### ISSUE TITLE
unauthorized program.cs:line 29 error dotnet run

### ISSUE THREAD

**Issue by saurabhksinha900** [microsoft/AISchoolTutorials#21]
C:\Users\saurabh.sinha\Downloads\AISchoolTutorials-master\AISchoolTutorials-master\sketch2code\Import>dotnet run

Unhandled Exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApi.GetDomainsWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApiExtensions.GetDomainsAsync(ITrainingApi operations, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApiExtensions.GetDomains(ITrainingApi operations)
   at Import.Program.Main(String[] args) in C:\Users\saurabh.sinha\Downloads\AISchoolTutorials-master\AISchoolTutorials-master\sketch2code\Import\Program.cs:line 29

**Comment by sabatale** [comment]
Same here. I don't think anyone is maintaining this repo anymore.

**Comment by leafygreens88** [comment]
> Same here. I don't think anyone is maintaining this repo anymore.

Same error isn't working for me either :( did you find a solution to it?

**Comment by srinivasdonglee** [comment]
I too facing the same exact issue,did any one of you fixed it,if so please reply with working solution

**Comment by harrybanda** [comment]
Same issue here

**Comment by harrybanda** [comment]
The solution that worked for me:
1. Open your terminal and go to Import folder
2. paste this `dotnet add package Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training --version 2.0.0`
this will update the CustomVision package.
3. Replace this line `TrainingApi trainingApi = new TrainingApi() { ApiKey = trainingKey };` with this line `CustomVisionTrainingClient trainingApi = new CustomVisionTrainingClient(new Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.ApiKeyServiceClientCredentials(trainingKey)) {Endpoint = ENDPOINT};`
makesure to replace `ENDPOINT` with your yours from [customvision.ai](https://www.customvision.ai/)
